### PR TITLE
Added TextButton element

### PR DESCRIPTION
**Pull request by WrinklyDog**

### CODE REVIEW

**Comment by Flaxis** [comment]
How would this be better than adding a SlickUI.Element.Text object to a SlickUI.Element.Button object (as seen [here](http://slick-ui.com/preview/menu.html))?

**Comment by WrinklyDog** [comment]
In parts of my game I don't want the actual button image. I could add a SlickUI.Element.Text object to a SlickUI.Element.Button with a transparent button image but then I couldn't use the regular button.  I would also have to add the text tint change on every button I created.

**Comment by Flaxis** [comment]
It sounds like you'd be better off forking the project then. We can't include code in the library that only facilitates specific situations. I did intend to write separate renderers for things such as buttons, panels etc. so maybe you'd be interested in that. I'll start working on that right now actually :)

**Comment by Flaxis** [comment]
Finished moving render responsibilities into separate objects. Maybe it interests you, because it gives you full control over rendering buttons. All you have to do, is reference it in your theme like this:

``` json
  "renderer": {
    "button": "Your.Namespace.Here.ButtonRenderer"
  },
```

You can refer to [the default ButtonRenderer](https://github.com/Flaxis/slick-ui/blob/master/src/Element/Renderer/ButtonRenderer.js) to find out how to make your own renderer.

See: 6b78e9df92336e0f3a93444f4b2ebc7590834846

I hope this helps you out! Unfortunately I can't merge your PR.

**Pull request closed without merging**
